fixed output incase one of the commands fails

diff --git a/scripts/grant_permissions_for_pyboard b/scripts/grant_permissions_for_pyboard
--- a/scripts/grant_permissions_for_pyboard
+++ b/scripts/grant_permissions_for_pyboard
@@ -11,6 +11,7 @@ done
 	exit 1
 }
 
+{
 sudo sh -c "cat > /etc/udev/rules.d/$a-pyboard.rules" <<EOF
 # f055:9800, 9801, 9802 MicroPython pyboard
 ATTRS{idVendor}=="f055", ENV{ID_MM_DEVICE_IGNORE}="1"
@@ -22,9 +23,11 @@ SYSFS{idVendor}=="f055", ENV{MTP_NO_PROBE}="1"
 SUBSYSTEMS=="usb", SYSFS{idVendor}=="f055", MODE="0666"
 KERNELS=="ttyACM*", SYSFS{idVendor}=="f055", MODE="0666"
 EOF
-echo "Rules were written to /etc/udev/rules.d/$a-pyboard.rules"
+} && echo "Rules were written to /etc/udev/rules.d/$a-pyboard.rules" || exit -1
 
 
-sudo udevadm control --reload-rules 1> /dev/null 2>&1 || udevcontrol reload_rules
+sudo udevadm control --reload-rules 1> /dev/null 2>&1 || sudo udevcontrol reload_rules || {
+echo "Could not reload rules."; exit 1
+}
 
 echo "Unplug and replug your device to activate the new rules. If this does not give you the right permissions, the new rules might be overridden by an other rule. In this case you can try to add the rules to a .rules file starting with a higher number."
diff --git a/scripts/remove_permissions_for_pyboard b/scripts/remove_permissions_for_pyboard
--- a/scripts/remove_permissions_for_pyboard
+++ b/scripts/remove_permissions_for_pyboard
@@ -36,6 +36,7 @@ KERNELS=="ttyACM*", SYSFS{idVendor}=="f055", MODE="0666"
 exit 1
 fi
 
-sudo udevadm control --reload-rules 1> /dev/null 2>&1 || udevcontrol reload_rules
+sudo udevadm control --reload-rules 1> /dev/null 2>&1 || sudo udevcontrol reload_rules ||{
+echo "Could not reload rules."; exit 1 }
 
 echo "udev rules were successfully reloaded"
